name: Update Markdown from JSON

on:
  push:
    paths:
      - 'leaderboard/leaderboard.json'

jobs:
  update-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to the latest version at the time of writing
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Generate Markdown
        run: python .github/scripts/generate-leaderboard.py
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add leaderboard/Leaderboard.md
          git commit -m "Update Leaderboard.md from JSON data" -a || echo "No changes to commit"
          git push
